name: fitbudd
description: A fitness companion app built with Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  lottie: ^3.3.1
  cupertino_icons: ^1.0.8
  fl_chart: ^0.66.2
  
  # State & Storage
  provider: ^6.1.5
  shared_preferences: ^2.2.2
  
  # Media
  image_picker: ^1.0.7
  
  # Utilities
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    # - assets/images/ (añade si tienes imágenes)
  # fonts: (añade si usas fuentes personalizadas)
  #   - family: ...